# Generated by Django 3.0.3 on 2020-04-25 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200413_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
